params:
  seed: 0
  algo:
    name: a2c_continuous

  env:
    clip_actions: 1.0

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: -0.5
        fixed_sigma: True
    mlp:
      input_size: 3456
      units: [512, 128, 64]
      activation: elu
      d2rl: False
      initializer:
        name: default
      regularizer:
        name: None

  load_checkpoint: False
  load_path: ""

  config:
    name: Kp
    device: cuda:0
    full_experiment_name: Robo_PP-v2
    env_name: rlgpu
    multi_gpu: False
    ppo: True
    mixed_precision: True
    normalize_input: True
    normalize_value: True
    value_bootstrap: True
    central_value: False
    num_actors: 1
    reward_shaper:
      scale_value: 1.0
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 5.0e-5
    lr_schedule: adaptive
    schedule_type: standard
    kl_threshold: 0.006
    score_to_win: 200000000000000000
    max_epochs: 200
    save_best_after: 10
    save_frequency: 100
    print_stats: True
    grad_norm: 1.0
    entropy_coef: 0.002
    truncate_grads: True
    e_clip: 0.2
    horizon_length: 256
    minibatch_size: 256
    mini_epochs: 3
    critic_coef: 2
    clip_value: True
    seq_length: 128
    bounds_loss_coef: 0.0001
    player:
      deterministic: False


